### ISSUE TITLE
请问数据预处理是怎样做的？

### ISSUE THREAD

**Issue by WangHonyu** [ZhouZineng/duration-forecast#1]
我尝试运行data_new/dataprocess.py来处理从赛题https://www.datafountain.cn/competitions/611/datasets 下载下来的数据，但遇到了报错
```
Traceback (most recent call last):
  File "/home/hongyuwang/.local/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 3803, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 138, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 165, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 5745, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 5753, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'sentence_chn'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/hongyuwang/MLassignment/duration-forecast/data_new/dataprocess.py", line 82, in <module>
    train_data,dic=read_data(train_file,train=True)
  File "/home/hongyuwang/MLassignment/duration-forecast/data_new/dataprocess.py", line 53, in read_data
    if isinstance(all_data.loc[idx, 'sentence_chn'], str):
  File "/home/hongyuwang/.local/lib/python3.10/site-packages/pandas/core/indexing.py", line 1066, in __getitem__
    return self.obj._get_value(*key, takeable=self._takeable)
  File "/home/hongyuwang/.local/lib/python3.10/site-packages/pandas/core/frame.py", line 3915, in _get_value
    series = self._get_item_cache(col)
  File "/home/hongyuwang/.local/lib/python3.10/site-packages/pandas/core/frame.py", line 4279, in _get_item_cache
    loc = self.columns.get_loc(item)
  File "/home/hongyuwang/.local/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 3805, in get_loc
    raise KeyError(key) from err
KeyError: 'sentence_chn'
```
请问该怎样预处理呢？

**Comment by ZhouZineng** [comment]
感谢您的反馈。我理解您遇到了运行代码的问题。实际上，该代码段是设计来处理整个文本文件的，其中的中文句子原本分为三个独立部分：判决文本、审理意见和法院意见。虽然最初的设计是将这些部分分开处理，但是由于一些原因，分割这些句子的具体代码并没有上传到GitHub。即便没有这部分分割代码，代码最后的性能差不多，只需要改一下读取的过程就好。

**Comment by zchoi** [comment]
您好，赛题数据有下载好的吗，竞赛页面下载不了了

**Comment by zchoi** [comment]
请问性能能达到多少呢，我跑出来dev acc一直是0.01

**Comment by ZhouZineng** [comment]
![image](https://github.com/ZhouZineng/duration-forecast/assets/70899230/c2e455be-0805-43da-ad5c-0010295b5a70)
这个是我们之前的排名
